catalog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect
from .views import *


urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^books/$', BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^mybooks/$', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^on_loan/$', BooksOnLoanListView.as_view(), name='all-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', renew_book_librarian, name='renew-book-librarian' ),
    re_path(r'^author/create/$', AuthorCreate.as_view(), name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', AuthorDelete.as_view(), name='author_delete'),
    re_path(r'^book/create/$', BookCreate.as_view(), name='book_create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', BookDelete.as_view(), name='book_delete')
]

locallibrary/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_catalog),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/catalog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect
from .views import *


urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^books/$', BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^mybooks/$', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^on_loan/$', BooksOnLoanListView.as_view(), name='all-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', renew_book_librarian, name='renew-book-librarian' ),
    re_path(r'^author/create/$', AuthorCreate.as_view(), name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', AuthorDelete.as_view(), name='author_delete'),
    re_path(r'^book/create/$', BookCreate.as_view(), name='book_create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', BookDelete.as_view(), name='book_delete')
]

templates/locallibrary/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_catalog),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.shortcuts import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length = 200, help_text = "Enter a book genre")

    def __str__(self):
        return self.name



#    def get_absolute_url(self):
#        return reverse('genre-detail', args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, null=True, blank=True)
    summary = models.TextField(max_length=1000, help_text = "Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,help_text = '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select  a genre for this book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null = True)

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_desciption = 'Genre'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def number_of_available(self):
        number = BookInstance.objects.filter(book__pk=self.pk).filter(status__exact = 'a')
        return number

    class Meta:
        ordering = ['title']

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text = "Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank = True)
    borrowed = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length = 1, choices = LOAN_STATUS, blank=True, default='m', help_text ="Book availability")

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return '{0}{1}'.format(self.id,self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null = True, blank = True)
    date_of_death = models.DateField('died', null = True, blank = True)
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0} {1}'.format(self.last_name, self.first_name)

    class Meta:
        ordering = ['last_name']

class Language(models.Model):
    name = models.CharField(max_length = 50, default = 'English',  help_text="Enter the book's natural language")

    def __str__(self):
        return self.name

templates/catalog/models.py
from django.db import models
from django.shortcuts import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length = 200, help_text = "Enter a book genre")

    def __str__(self):
        return self.name



#    def get_absolute_url(self):
#        return reverse('genre-detail', args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, null=True, blank=True)
    summary = models.TextField(max_length=1000, help_text = "Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,help_text = '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select  a genre for this book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null = True)

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_desciption = 'Genre'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def number_of_available(self):
        number = BookInstance.objects.filter(book__pk=self.pk).filter(status__exact = 'a')
        return number

    class Meta:
        ordering = ['title']

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text = "Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank = True)
    borrowed = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length = 1, choices = LOAN_STATUS, blank=True, default='m', help_text ="Book availability")

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return '{0}{1}'.format(self.id,self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null = True, blank = True)
    date_of_death = models.DateField('died', null = True, blank = True)
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0} {1}'.format(self.last_name, self.first_name)

    class Meta:
        ordering = ['last_name']

class Language(models.Model):
    name = models.CharField(max_length = 50, default = 'English',  help_text="Enter the book's natural language")

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = 'Enter a date between now and 4 weeks (default 3).', label_suffix=': ')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks = 4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

templates/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = 'Enter a date between now and 4 weeks (default 3).', label_suffix=': ')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks = 4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import ValidationError
import datetime

from .forms import RenewBookForm
from .models import *


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    num_books_filter = Book.objects.filter(title__icontains = 'lord').count()
    return render(request, 'index.html', context = {'num_books':num_books, 'num_instances' : num_instances, 'num_instances_available' : num_instances_available, 'num_authors' : num_authors, 'num_genres' : num_genres, 'num_books_filter':num_books_filter, 'num_visits': num_visits})

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    return render(request, 'book_renew_librarian.html', {'form': form, 'bookinst':book_inst})


class BookListView(ListView):
    model = Book
    template_name = 'books_list.html'
    paginate_by = 10
#    def get_queryset(self):
#        return Book.objects.filter(title__icontains='of')[:5] #5 books with 'of' in title

#    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
#        context = super(BookListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и иниуиализируем ее некоторым значением
#        context['some_data'] = 'This is just some data'
#        return context

class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'

class AuthorListView(ListView):
    model = Author
    template_name = 'authors_list.html'
    paginate_by = 10

class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'
    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['book_list'] = Book.objects.filter(author__pk=self.kwargs.get('pk'))
        context['books_instances_available'] = Book.objects.filter(author__pk=self.kwargs.get('pk'))
        return context

class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrowed=self.request.user).filter(status__exact='o').order_by('due_back')

class BooksOnLoanListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'books_on_loan_list.html'
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial={'date_of_death':'2019-02-27',}
    template_name = 'author_form.html'
    permission_required = 'catalog.add_author'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    template_name = 'author_form.html'
    permission_required = 'catalog.change_author'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    template_name = 'author_confirm_delete.html'
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    template_name = 'book_form.html'
    permission_required = 'catalog.add_book'

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'book_form.html'
    permission_required = 'catalog.change_book'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    template_name = 'book_confirm_delete.html'
    success_url = reverse_lazy('books')
    permission_required = 'catalog.delete_book'

catalog/templates/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>
  <p> ({{author.date_of_birth}} - {% if author.date_of_death %} {{author.date_of_death}} {% endif %})</p>
  <h3> Books </h3>
  {% if book_list %}
  <ul>

   {% for book in book_list %}
    <li type=none>
      <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
      <b> ({{ book.number_of_available|length }})</b>
      <p>{{book.summary}}</p>
    </li>
    {% endfor %}

  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}

{% endblock %}

catalog/templates/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/authors_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Authors List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }} {{ author.first_name}} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})</a>
        {% if user.is_staff or user.groups.all.0.name == 'Librarians' %}
        <table><tr>
          <td><form action="{% url 'author_update' author.pk %}"> <input type="submit" value="Update" /></form></td>
          <td><form action="{% url 'author_delete' author.pk %}"> <input type="submit" value="Delete" /></form></td>
        </tr></table>
        {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}"> {{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %},{% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>




    {% for copy in book.bookinstance_set.all %}

    <!--
    bookinstance_set создан, потому что вы, на стороне "многим" данной связи, объявили поле ForeignKey (один-ко многим). Поскольку вы ничего не объявили на другой стороне ("один") данной модели (то есть, модель Book "ничего не знает" про модель BookInstance), то она не имеет никакой возможности (по умолчанию) для получения множества соответствующих записей. Для того, чтобы обойти эту проблему, Django конструирует соответствующую функцию "обратного просмотра" ("reverse lookup"), которой вы можете воспользоваться. Имя данной функции создается в нижнем регистре и состоит из имени модели, в которой был объявлен ForeignKey (то есть, bookinstance), за которым следует _set (то есть функция, созданная для Book будет иметь вид bookinstance_set()).
      -->

    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/book_renew_librarian.html
{% extends 'base_generic.html'%}
{% block content %}


<h1> Renew: {{bookinst.book.title}}</h1>
<p>Borrower: {{bookinst.borrowed}}</p>
<p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

<form action="" method="post">
  {% csrf_token %}

    {{form.as_table}}

  <input type="submit" name="Submit">

</form>

{% endblock %}

catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/books_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Books List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
        {% if user.is_staff or user.groups.all.0.name == 'Librarians' %}
        <table><tr>
          <td><form action="{% url 'book_update' book.pk %}"> <input type="submit" value="Update" /></form></td>
          <td><form action="{% url 'book_delete' book.pk %}"> <input type="submit" value="Delete" /></form></td>
        </tr></table>
        {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/books_on_loan_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrowed }}
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends 'base_generic.html' %}


{% block title %} <title>Catalog</title> {% endblock %}
{% block content %}
<h1>Local Library Home</h1>
<p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>



<h2> Dynamic content </h2>


<p> The library has the following record counts: </p>

<ul>
  <li><strong>Books: </strong>{{num_books}}</li>
  <li><strong>Copies: </strong>{{num_instances}}</li>
  <li><strong>Copies available: </strong>{{num_instances_available}}</li>
  <li><strong>Authors: </strong>{{num_authors}}</li>
  <li><strong>Genres: </strong>{{num_genres}}</li>
  <li><strong>Books includes "Lord" in title: </strong>{{num_books_filter}}</li>
</ul>
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}